name: "AHK evaluation result"
description: "Processes a text log file that is the result of a student work evaluation and publishes the result into a Pull Request"
inputs:
  github-token:
    description: "The GITHUB_TOKEN secret"
    required: true
  input-file:
    description: "The path of the input file containing the evaluation result. When specified, the parsed results will be included in the result comment."
    required: false
    default: "result.txt"
  image-extension:
    description: "The extension of image files (with leading dot). When specified, the images are include in the result comment."
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
